### ISSUE TITLE
Divide the cost of relaying blocks among all data requests using those blocks as PoI

### ISSUE THREAD

**Issue by girazoki** [witnet/witnet-ethereum-bridge#140]
To be investigated, but a potential approach is to count how many PoIs have been done with the same block, and divide the cost among them

**Comment by mariocao** [comment]
Today we discussed a simpler approach to avoid that the BlockRelay contract ends up with requestor funds:

 - pay the block relayer only once.
 - next data requests will return the block reward to the DR creator.

This approach is not ideal but it has the advantage of being quite simple and does not need to store additional data in contracts (e.g. list of request creator addresses...)
