### ISSUE TITLE
Define RADON errors for signaling that Data Requests cannot be relayed

### ISSUE THREAD

**Issue by mariocao** [witnet/witnet-ethereum-bridge#156]
In the incoming bridge design it will be possible that data requests cannot be relayed due to different reasons:
- data request is not accepted by the Witnet client due to invalid parameter (e.g. exceeds maximum number of witneseses)
- data request parameters exceed a bridge-operator-defined threshold (e.g. collateral) --> mitigates funds drainage and attacks
- data request result length exceeds a bridge-contract-defined limit (in bytes) --> limits funds drainage

This issue should include the new definition of those RADON errors in `witnet-rust`, but also in the `Witnet.sol` contract.

**Comment by lrubiorod** [comment]
Done in #158
