### ISSUE TITLE
ABS design

### ISSUE THREAD

**Issue by aesedepece** [witnet/witnet-ethereum-bridge#25]

**Comment by girazoki** [comment]
# Active Bridge Set Design Proposal
<sup>_This proposal has been drafted by the Witnet Foundation dev team. Discussion is open for other members in the Witnet community to suggest changes or come up with a totally different proposal. This document is therefore to be understood as a recommendation but not as an specification that will necessarily be implemented._</sup>

## Context
Bridge nodes need to be eligible to be able to introduce data requests into the Witnet protocol. This eligibility is calculated by the following equation

VRF(m)<sub>i></sub>/2<sup>256</sup> < R/ABS

Where VRF(m)<sub>i></sub> is just the VRF output of identity i, R is the replication factor (how many nodes we want on average to be eligible) and ABS refers to the number of nodes that have been active over the last _λ<sub>a</sub> number of blocks, which we call slots.

## Data structures

We propose a data structure, _ActiveBridgeSet_, with the following fields,

- `epochIdentities`: a mapping that keeps track of the number of identities.
