### ISSUE TITLE
Prevent New Block Relay Double Voting

### ISSUE THREAD

**Issue by girazoki** [witnet/witnet-ethereum-bridge#48]
As of today the New Block Relay implements the finality gadget but does not prevent double voting from ABS members. This issue should provide the following features:

- Prevent an ABS member from voting twice in the same epoch.

**Comment by mariocao** [comment]
Closed by da0fad01285804f47a676d449ea676f3a172538d

**Comment by mariocao** [comment]
Closed by da0fad01285804f47a676d449ea676f3a172538d
