### ISSUE TITLE
Yarn.lock should not be committed in libraries

### ISSUE THREAD

**Issue by aesedepece** [witnet/witnet-ethereum-bridge#63]
This repository is imported as a library in other Witnet repositories.

As a rule of thumb, `yarn.lock` should not be committed in libraries. Otherwise, we lose the flexibility of targeting specific branches, because the lock file picks a specific commit that is not upgradeable.

**Comment by aesedepece** [comment]
I now there's controversy around this in the JS space, but being pragmatic this is the best option for us at this point.

**Comment by mariocao** [comment]
Closed in 24a7bd3338b9657bc2ee53daaa7e190b059e3bef
