### ISSUE TITLE
Drain of Contract Funds that could trigger a Denial of Service

### ISSUE THREAD

**Issue by alvarodh5** [witnet/witnet-ethereum-bridge#75]
Finding discovered during Red4Sec security audit.

## Description
Reviewing _**WitnetRequestBoard**_ smart contract it was detected that the reportResult method incorrectly implements the logic necessary to verify whether a result has been previously included or not. 
&nbsp;

## Impact
This failure could tentatively  cause a drain on the contract funds by any attacker and produce a denial of service.
&nbsp;

## Steps to reproduce
As we can see in the following screenshot, there is a modifier called resultNotIncluded, which uses the size of the result to check whether or not it has been previously included. It should be noted that a result can also be empty ("").

![image](https://user-images.githubusercontent.com/9592881/79152537-ac8ddc80-7dcc-11ea-9919-2938b5d79530.png)

&nbsp;
In the **_CBOR_** library it is checked that the size is greater than 0 to consider it a valid CBOR, so the modifier that has been observed in the previous image, apparently would turn out to be valid.

![image](https://user-images.githubusercontent.com/9592881/79152559-b6afdb00-7dcc-11ea-89f2-6c3942a84e4d.png)
&nbsp;

However, as can be seen in the following image, it is not verified that the result is a valid CBOR. This verification is only done during reading and not during reporting. This would allow us to bypass the _resultNotIncluded_ modifier in case an empty result ("") is sent.
In this way, it would be possible to collect the fee for said result without marking it as consumed, being able to send the same transaction recursively and collecting the same fee from the contract funds and not from the part reserved for the bridge that serves it.

In this way, the attacker could completely drain the funds from the _WitnetRequestBoard_ contract, in turn making a _Denial of Service_ (DoS), since the bridges could not receive the fee they had intended to carry out their work and therefore the execution of their transactions would fail.

![image](https://user-images.githubusercontent.com/9592881/79152609-ca5b4180-7dcc-11ea-9600-77f5492b7f7f.png)

&nbsp;
## Code References
https://github.com/witnet/witnet-ethereum-bridge/blob/9d1f3be651ac644056303d18c20eecc4fc490472/contracts/WitnetRequestsBoard.sol#L101

https://github.com/witnet/witnet-ethereum-bridge/blob/9d1f3be651ac644056303d18c20eecc4fc490472/contracts/WitnetRequestsBoard.sol#L224
&nbsp;

## Mitigation
It is recommended to add a boolean type field in the DataRequest struct as a flag to check whether the result has already been reported or not.

**Comment by girazoki** [comment]
what about checking whether the inserted result length is >0? we know that results coded in CBOR should never have a length=0. What do you think about it?
