### ISSUE TITLE
Insufficient consensus error reverts in price feed smart contract

### ISSUE THREAD

**Issue by girazoki** [witnet/witnet-ethereum-bridge#80]
In particular de following bytes trigger the error. 39([81, 0.5, 0.7]). We should investigate why this happens as this stalls the price feed contract

**Comment by aesedepece** [comment]
It happens because it is an assumption of the `Witnet` library that error payloads are `uint64[]`, but the Witnet node is encoding percentages as floating point numbers :sweat:

**Comment by girazoki** [comment]
We tried putting a try-catch in the Witnet library but since it should to support multiple versions, and the try catch with `memory` identifiers was only working after 0.6.6, we decided to fix it in the client contracts. This issue has been closed by bf42e2830a33c1e4082890d07c78867f04c26bf6
