### ISSUE TITLE
Possible Burn of Funds while updating Data Request

### ISSUE THREAD

**Issue by alvarodh5** [witnet/witnet-ethereum-bridge#83]
Finding discovered during [Red4Sec](https://red4sec.com) security audit.

## Description
Red4Sec team has detected a high impact vulnerability that in case of occurring could cause the burn of funds due to a bad implementation in _upgradeDataRequest()_ function located in WitnetRequestBoard.sol contract. 
&nbsp;

## Impact
Burn of funds due to a bad implementation in _upgradeDataRequest()_ function.
&nbsp;

## Steps to reproduce
This fault has been located between lines 166-168 of the contract and its produced because the function does not include a _require()_ that verifies the current status of the request.
The current state of the request should be verified by means of a require, since it could happen that the claim arrives before the user tries to extend the fee, which would burn that fee. In the same way, it could happen with publish, that is why it is necessary to carry out the appropriate checks to revert or not the transaction.

![image](https://user-images.githubusercontent.com/9592881/80283809-cc9d9400-871a-11ea-98ff-e698eb933766.png)
&nbsp;

## Code Reference
https://github.com/witnet/witnet-ethereum-bridge/blob/cf4ffe9434be79ec29079a3fcaf885adfb213cb8/contracts/WitnetRequestsBoard.sol#L166-L168
&nbsp;

## Mitigation
Check the status of the contract request to revert or not the fee expansion, and thus avoid unnecessary loss of ether.

**Comment by mariocao** [comment]
Closed by #86
