### ISSUE TITLE
Error Solidity tests

### ISSUE THREAD

**Issue by clbartoli** [witnet/witnet-ethereum-bridge#89]
The following tests do not pass

- TestActiveBridgeSet.sol
- TestBuffer.sol
-TestCBOR.sol

The error message is `Error: Could not find artifacts for /home//witnet-ethereum-bridge/contracts/flattened/Flattened.sol from any sources`

**Comment by girazoki** [comment]
I just tried deleting the flattened.sol file and everything works fine. The problem is we probably had the flattened.sol contract already generated from another branch and that was causing errors
