### ISSUE TITLE
Assess reporting of RadonTypes in Solidity

### ISSUE THREAD

**Issue by aesedepece** [witnet/witnet-ethereum-bridge#9]

**Comment by aesedepece** [comment]
My points so far:
- We may need a `Result` contract that encapsulates the classical `Ok`/`Err` functionality.
  ```solidity
  contract Result {
    enum Variant { Ok, Error }

    enum Error {
      RuntimeError,
      InsufficientConsensusError
    }

    Variant variant;
    bytes value;
    Error error;

    function isOk () public view returns(bool) {
      return variant == Variant.Ok;
    }
  }
  ```
- `witnetReadResult` can then look like:
  ```solidity
  function witnetReadResult (Request _dr) public returns(Result){
    return new Result(wbi.readResult(uint256(_dr.id())));
  }
  ```
- Contracts can decide on the result like this:
  ```solidity
  if (result.isOk()) { /* ... */ } else { /* ... */ }
  ```
- The inner value of the `Result` can be then safely retrieved inside the positive branch thanks to `as` methods:
  ```solidity
  function asBytes () public view returns(bytes memory) {
    assert(variant == Variant.Ok);
    return value;
  }
  ```
  That's of course a dummy one. Other methods like `asUint256` should internally perform the decoding of the bytes.
- **There's no MessagePack implementation in Solidity**
  - We can write our own
  - We can move to CBOR, which is gaining more traction than MsgPack recently and has a Solidity implementation

**Comment by mariocao** [comment]
The results of this assessment are in the PR #21
